name: Build and store in artifacts

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: commit
        uses: pr-mpt/actions-commit-hash@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
      - name: Install dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk
      - name: Upload APK to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ steps.commit.outputs.short }}
          path: build/app/outputs/apk/release/app-release.apk
          retention-days: 7

  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: commit
        uses: pr-mpt/actions-commit-hash@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
          architecture: x64
      - name: Install dependencies
        run: flutter pub get
      - name: Build for macOS
        run: flutter build macos
      - name: Pack app to tarball
        run: tar -czvf build-mac.tar build/macos/Build/Products/Release/BAZMAN.app
      - name: Upload result to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-mac-${{ steps.commit.outputs.short }}
          path: build-mac.tar
          retention-days: 7
