name: Build web app and deploy to Github Pages

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: commit
        uses: pr-mpt/actions-commit-hash@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
          cache: true
      - name: Install dependencies
        run: flutter pub get
      - name: Build and deploy to Github Pages
        uses: bluefireteam/flutter-gh-pages@v7
        with:
          webRenderer: canvaskit
